[2024-03-25T00:44:06.614+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T00:43:55.951324+00:00 [queued]>
[2024-03-25T00:44:06.619+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T00:43:55.951324+00:00 [queued]>
[2024-03-25T00:44:06.619+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-25T00:44:06.626+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_clean_to_parquet_task> on 2024-03-25 00:43:55.951324+00:00
[2024-03-25T00:44:06.631+0000] {standard_task_runner.py:60} INFO - Started process 2167 to run task
[2024-03-25T00:44:06.634+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_clean_to_parquet_task', 'manual__2024-03-25T00:43:55.951324+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpjxov67d2']
[2024-03-25T00:44:06.636+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask do_clean_to_parquet_task
[2024-03-25T00:44:06.664+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T00:43:55.951324+00:00 [running]> on host 9654d883592e
[2024-03-25T00:44:06.707+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_clean_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:43:55.951324+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T00:43:55.951324+00:00'
[2024-03-25T00:44:08.370+0000] {warnings.py:109} WARNING - /opt/***/dags/book-recommendation-dag.py:15: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_df = pd.read_csv(f'{dataset_download_path}{filename}')

[2024-03-25T00:44:08.441+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 25, in do_clean_to_parquet
    dataset_df = dataset_df.rename(columns={
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5432, in rename
    return super()._rename(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 992, in _rename
    raise TypeError(
TypeError: Cannot specify both 'axis' and any of 'index' or 'columns'
[2024-03-25T00:44:08.453+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=do_clean_to_parquet_task, execution_date=20240325T004355, start_date=20240325T004406, end_date=20240325T004408
[2024-03-25T00:44:08.465+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task do_clean_to_parquet_task (Cannot specify both 'axis' and any of 'index' or 'columns'; 2167)
[2024-03-25T00:44:08.509+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T00:44:08.561+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
