[2024-03-25T03:39:09.578+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T03:37:59.818463+00:00 [queued]>
[2024-03-25T03:39:09.584+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T03:37:59.818463+00:00 [queued]>
[2024-03-25T03:39:09.584+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-03-25T03:39:09.593+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_clean_to_parquet_task> on 2024-03-25 03:37:59.818463+00:00
[2024-03-25T03:39:09.598+0000] {standard_task_runner.py:60} INFO - Started process 4001 to run task
[2024-03-25T03:39:09.601+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_clean_to_parquet_task', 'manual__2024-03-25T03:37:59.818463+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpn738cs2i']
[2024-03-25T03:39:09.604+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask do_clean_to_parquet_task
[2024-03-25T03:39:09.645+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T03:37:59.818463+00:00 [running]> on host 9654d883592e
[2024-03-25T03:39:09.710+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_clean_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T03:37:59.818463+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T03:37:59.818463+00:00'
[2024-03-25T03:39:11.059+0000] {warnings.py:109} WARNING - /opt/***/dags/book-recommendation-dag.py:24: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_df = pd.read_csv(f'{dataset_download_path}{filename}')

[2024-03-25T03:39:11.083+0000] {logging_mixin.py:188} INFO - dataset_df.dtypes1 ISBN                   object
Book-Title             object
Book-Author            object
Year-Of-Publication    object
Publisher              object
Image-URL-S            object
Image-URL-M            object
Image-URL-L            object
dtype: object
[2024-03-25T03:39:11.117+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 43, in do_clean_to_parquet
    dataset_df.astype(books_dtype)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6290, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'ISBN' not found in columns."
[2024-03-25T03:39:11.123+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=do_clean_to_parquet_task, execution_date=20240325T033759, start_date=20240325T033909, end_date=20240325T033911
[2024-03-25T03:39:11.131+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 68 for task do_clean_to_parquet_task ("Only a column name can be used for the key in a dtype mappings argument. 'ISBN' not found in columns."; 4001)
[2024-03-25T03:39:11.169+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T03:39:11.185+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
