[2024-03-26T01:47:08.423+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.create_table_partitions_task manual__2024-03-26T01:46:48.591069+00:00 [queued]>
[2024-03-26T01:47:08.428+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.create_table_partitions_task manual__2024-03-26T01:46:48.591069+00:00 [queued]>
[2024-03-26T01:47:08.428+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-26T01:47:08.435+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryInsertJobOperator): create_table_partitions_task> on 2024-03-26 01:46:48.591069+00:00
[2024-03-26T01:47:08.439+0000] {standard_task_runner.py:60} INFO - Started process 3140 to run task
[2024-03-26T01:47:08.441+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'create_table_partitions_task', 'manual__2024-03-26T01:46:48.591069+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpg1c5lfgr']
[2024-03-26T01:47:08.443+0000] {standard_task_runner.py:88} INFO - Job 320: Subtask create_table_partitions_task
[2024-03-26T01:47:08.465+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.create_table_partitions_task manual__2024-03-26T01:46:48.591069+00:00 [running]> on host 992e1288d09b
[2024-03-26T01:47:08.502+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='create_table_partitions_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T01:46:48.591069+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T01:46:48.591069+00:00'
[2024-03-26T01:47:08.503+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-26T01:47:08.503+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-26T01:47:08.504+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-26T01:47:08.504+0000] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2024-03-26T01:47:08.544+0000] {bigquery.py:2811} INFO - Executing: {'query': {'query': 'DROP TABLE IF EXISTS `book_recommendation_analytics.books`;\n\nCREATE TABLE IF NOT EXISTS\n  `book_recommendation_analytics.books`\nPARTITION BY YEAR(years_of_publication)\nCLUSTER BY\n  `years_of_publication`,\n  `publisher`,\n  `book_author` AS\nSELECT\n  *\nFROM\n  `book_recommendataion_wh.books`;', 'useLegacySql': False}}'
[2024-03-26T01:47:08.545+0000] {bigquery.py:1613} INFO - Inserting job ***_Book_Recommendation_DAG_create_table_partitions_task_2024_03_26T01_46_48_591069_00_00_32b8648dc145447a4d51a0227cd4c5a1
[2024-03-26T01:47:10.188+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2870, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Query error: Function not found: YEAR at [5:14]

Location: us-west1
Job ID: airflow_Book_Recommendation_DAG_create_table_partitions_task_2024_03_26T01_46_48_591069_00_00_32b8648dc145447a4d51a0227cd4c5a1

[2024-03-26T01:47:10.207+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=create_table_partitions_task, execution_date=20240326T014648, start_date=20240326T014708, end_date=20240326T014710
[2024-03-26T01:47:10.222+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 320 for task create_table_partitions_task (400 Query error: Function not found: YEAR at [5:14]

Location: us-west1
Job ID: airflow_Book_Recommendation_DAG_create_table_partitions_task_2024_03_26T01_46_48_591069_00_00_32b8648dc145447a4d51a0227cd4c5a1
; 3140)
[2024-03-26T01:47:10.266+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-26T01:47:10.283+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
