[2024-03-25T19:57:00.446+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:55:47.069159+00:00 [queued]>
[2024-03-25T19:57:00.451+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:55:47.069159+00:00 [queued]>
[2024-03-25T19:57:00.452+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-03-25T19:57:00.458+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_upload_pq_to_gcs_task> on 2024-03-25 19:55:47.069159+00:00
[2024-03-25T19:57:00.464+0000] {standard_task_runner.py:60} INFO - Started process 543 to run task
[2024-03-25T19:57:00.471+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_upload_pq_to_gcs_task', 'manual__2024-03-25T19:55:47.069159+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpqvucehrm']
[2024-03-25T19:57:00.480+0000] {standard_task_runner.py:88} INFO - Job 229: Subtask do_upload_pq_to_gcs_task
[2024-03-25T19:57:00.520+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:55:47.069159+00:00 [running]> on host 992e1288d09b
[2024-03-25T19:57:00.567+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_upload_pq_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T19:55:47.069159+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T19:55:47.069159+00:00'
[2024-03-25T19:57:00.575+0000] {logging_mixin.py:188} INFO - gcs_pq_store_path book_recommendation_datalake_radiant-gateway-412001/book-recommendation-pq
[2024-03-25T19:57:00.702+0000] {logging_mixin.py:188} INFO - dir_info.type FileType.NotFound
[2024-03-25T19:57:00.703+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 119, in do_upload_pq_to_gcs
    gcs.create_dir(gcs_pq_store_path)
NameError: name 'gcs_path' is not defined
[2024-03-25T19:57:00.710+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=do_upload_pq_to_gcs_task, execution_date=20240325T195547, start_date=20240325T195700, end_date=20240325T195700
[2024-03-25T19:57:00.719+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 229 for task do_upload_pq_to_gcs_task (name 'gcs_path' is not defined; 543)
[2024-03-25T19:57:00.737+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T19:57:00.752+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
